# Setup
title:        WorkflowHub
tagline:      Community Framework for Enabling Scientific Workflow Research and Development
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Rafael Ferreira da Silva
  url:        http://rafaelsilva.com

#Others
markdown: kramdown
